/*
 _____    _ _             _   _ ___ _____         _ _   _ _
|_   _| _(_) |_ ___ _ _  | | | |_ _|_   _|__  ___| | |_(_) |_
  | || '_| |  _/ _ \ ' \ | |_| || | _| |/ _ \/ _ \ | / / |  _|
  |_||_| |_|\__\___/_||_(_)___/|___(_)_|\___/\___/_|_\_\_|\__|

Copyright © 2024, Michel Gerritse
All rights reserved.

This source code is available under the BSD-3-Clause license.
See LICENSE.txt in the root directory of this source tree.

*/
namespace Triton.UI.Extensions
{
	[default_interface]
	runtimeclass BitmapIconExtension : Microsoft.UI.Xaml.Markup.MarkupExtension
	{
		BitmapIconExtension();

		/* BitmapIcon properties */
		Boolean ShowAsMonochrome;
		Windows.Foundation.Uri UriSource;

		/* BitmapIcon properties inherited from IconElement */
		Microsoft.UI.Xaml.Media.Brush Foreground;
	}
}