/*
 _____    _ _             _   _ ___ _____         _ _   _ _
|_   _| _(_) |_ ___ _ _  | | | |_ _|_   _|__  ___| | |_(_) |_
  | || '_| |  _/ _ \ ' \ | |_| || | _| |/ _ \/ _ \ | / / |  _|
  |_||_| |_|\__\___/_||_(_)___/|___(_)_|\___/\___/_|_\_\_|\__|

Copyright © 2024, Michel Gerritse
All rights reserved.

This source code is available under the BSD-3-Clause license.
See LICENSE.txt in the root directory of this source tree.

*/
namespace Triton.UI.Controls
{
	[default_interface]
	runtimeclass SettingsExpander : Microsoft.UI.Xaml.Controls.Control
	{
		SettingsExpander();

		Object Content;
		static Microsoft.UI.Xaml.DependencyProperty ContentProperty{ get; };

		Object HeaderIcon;
		static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty{ get; };

		Object Header;
		static Microsoft.UI.Xaml.DependencyProperty HeaderProperty{ get; };

		Object Description;
		static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty{ get; };

		/*Microsoft.UI.Xaml.UIElement ItemsHeader;
		static Microsoft.UI.Xaml.DependencyProperty ItemsHeaderProperty{ get; };
		
		Microsoft.UI.Xaml.UIElement ItemsFooter;
		static Microsoft.UI.Xaml.DependencyProperty ItemsFooterProperty{ get; };
		
		Boolean IsExpanded;
		static Microsoft.UI.Xaml.DependencyProperty IsExpandedProperty{ get; };*/
	}
}